#ifndef NCR_COMMON_H
#define NCR_COMMON_H

#define UART_BAUD 460800
#define CAN_BAUD 500000

typedef enum {
    TELEMETRY_PACKET = 0x10,
    COMMAND_PACKET = 0x20
} PACKET_TYPE;

typedef enum {
  LED_COMMAND = 0x01,
  VALVE_COMMAND = 0x02,
  PT_CALIBRATION_COMMAND = 0x03,
  MODE_COMMAND = 0x04
} COMMAND_TYPE;

typedef enum {
  VOLTAGE_TELEMETRY = 0x01,
  PRESSURE_TELEMETRY = 0x02,
  TEMPERATURE_TELEMETRY = 0x03,
  WEIGHT_TELEMETRY = 0x04
} TELEMETRY_TYPE;

#endif // NCR_COMMON_H